services:

  db:
    image: mysql:8.0
    container_name: innovatech-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - innovatech-net

  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: innovatech-backend-ventas
    restart: unless-stopped
    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: ventas_db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - innovatech-net

  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: innovatech-backend-despachos
    restart: unless-stopped
    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: despachos_db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - innovatech-net

  frontend:
    build:
      context: ./front_despacho
    environment:
      - VITE_API_VENTAS_URL=http://localhost:8080
      - VITE_API_DESPACHOS_URL=http://localhost:8081
    container_name: innovatech-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - innovatech-net

networks:
  innovatech-net:
    driver: bridge

volumes:
  db_data:
